# docker-compose.yml
version: '3.8'

services:
  juice-shop:
    image: bkimminich/juice-shop:v16.0.0
    ports:
      - "4000:4000"
    restart: always

  zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    container_name: owasp-zap
    ports:
      - "8080:8080" # UI ของ ZAP (ไม่จำเป็นต้องใช้ใน CI/CD แต่บางคนอาจอยากเห็น)
      - "8090:8090" # Port สำหรับ ZAP API (สำคัญสำหรับการสั่งงาน)
    # Volumes ไม่จำเป็นต้องใช้ใน CI/CD ถ้าไม่ได้ต้องการเก็บ persistent data ระหว่าง job
    # command: ["zap.sh", "-daemon", "-port", "8090", "-host", "0.0.0.0", "-config", "api.disablekey=true", "-config", "api.addrs.addr.name=.*", "-config", "api.addrs.addr.regex=true"]
    # สำหรับ CLI จะใช้ ZAP's built-in automation framework
    # command: ["zap.sh", "-cmd"] # หรือไม่ต้องใส่ command ถ้าจะให้ ZAP รัน default daemon
    depends_on:
      - juice-shop