version: 2.1

orbs:
  cypress: cypress-io/cypress@3

workflows:
  build:
    jobs:
      - cypress/run:
          name: Run Cypress Tests
          install-command: npm ci
          start-command: echo 'No dev server needed'
          cypress-command: npx cypress run --record --parallel
          parallelism: 2
