name: ZAP API Scan (Petstore OpenAPI)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # อนุญาตให้รันด้วยมือ

jobs:
  api-scan:
    runs-on: ubuntu-latest
    name: Scan Petstore OpenAPI

    permissions:
      issues: write # ให้สิทธิ์ในการสร้าง Issue (ถ้าต้องการ)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run ZAP API Scan on Petstore OpenAPI
      uses: zaproxy/action-api-scan@v0.9.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        # Target คือ URL ของ OpenAPI JSON definition
        target: 'https://petstore.swagger.io/v2/swagger.json'
        format: openapi # ระบุว่า target เป็น OpenAPI
        docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
        # cmd_options: '-a' # เปิด Active Scan (อาจใช้เวลานานขึ้น)
        # cmd_options: '-r /zap/wrk/report_html.html -J /zap/wrk/report_json.json' # กำหนดชื่อไฟล์รายงานเอง
        allow_issue_writing: true # อนุญาตให้สร้าง GitHub Issue

    - name: Upload ZAP API Scan Reports
      uses: actions/upload-artifact@v4
      with:
        name: petstore-api-scan-reports
        path: ./*.html # หรือ ./* เพื่อรวมรายงานทั้งหมดที่สร้างใน root
        retention-days: 7