name: ZAP DAST Scan with Juice Shop

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows running manually

jobs:
  dast-scan:
    runs-on: ubuntu-latest
    name: Scan Juice Shop Web Application
    permissions:
      # เพิ่มบรรทัดนี้: ให้สิทธิ์ในการเขียน (write) issues
      issues: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Start Juice Shop
      # Run Juice Shop directly, mapping container port 3000 to host port 4000
      run: |
        docker run -d -p 4000:3000 --name juice-shop-container bkimminich/juice-shop:v16.0.0
        echo "Juice Shop container started on port 4000."

    - name: Wait for Juice Shop to be ready
      # Check if Juice Shop is ready on localhost:4000 of the GitHub Actions runner
      run: |
        echo "Waiting for Juice Shop (http://localhost:4000) to be ready..."
        for i in $(seq 1 60); do # Wait up to 60 seconds
          curl -s http://localhost:4000 > /dev/null && break
          echo "Juice Shop not ready yet, waiting 1 second..."
          sleep 1
          if [ $i -eq 60 ]; then
            echo "Error: Juice Shop did not start in time. Exiting."
            exit 1
          fi
        done
        echo "Juice Shop is ready on port 4000."

    - name: Run ZAP Scan (using pre-built action)
      uses: zaproxy/action-baseline@v0.14.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target: 'http://localhost:4000' # ZAP will scan Juice Shop on port 4000
        cmd_options: '-a'
        allow_issue_writing: true # ตรวจสอบให้แน่ใจว่าตัวเลือกนี้เป็น true

    - name: Upload ZAP Reports
      uses: actions/upload-artifact@v4
      with:
        name: zap-scan-reports
        path: zap_report/
        retention-days: 7

    - name: Stop Juice Shop container
      # Cleanup: Stop and remove the Juice Shop container
      if: always() # Run this step always, regardless of success or failure
      run: |
        docker stop juice-shop-container
        docker rm juice-shop-container