name: 🛡️ ZAP Scan Juice Shop

on:
  workflow_dispatch: # อนุญาตให้สั่งรัน workflow ด้วยตนเองจากหน้า Actions ใน GitHub
  push:
    branches:
      - main # หรือ branch หลักของคุณ

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: 📚 Checkout code
        uses: actions/checkout@v4

      - name: 📁 Create ZAP Configuration and Report Directories
        run: |
          mkdir -p zap-config
          mkdir -p zap-reports

      - name: 📝 Create ZAP Automation Plan
        shell: bash
        run: |
          cat <<EOF > zap-config/automation_plan.yaml
          # ZAP Automation Framework Plan
          # https://www.zaproxy.org/docs/automate/automation-framework/

          env:
            contexts: # กำหนด context สำหรับการสแกน
              - name: 'Juice Shop Target'
                urls:
                  - 'http://localhost:3000' # URL ของ Juice Shop
                includePaths: # ระบุ path ที่ต้องการสแกน (regex)
                  - 'http://localhost:3000.*'
                # excludePaths: # (Optional) ระบุ path ที่ไม่ต้องการสแกน (regex)
                #   - 'http://localhost:3000/rest/user/logout.*'
            parameters:
              failOnError: true       # หยุดการทำงานหากมี error
              failOnWarning: false    # ไม่หยุดหากมีแค่ warning
              progressToStdout: true  # แสดง progress ออกทาง stdout

          jobs:
            # Job: อัปเดต Add-ons (แนะนำให้ทำเพื่อให้ได้ rules ล่าสุด)
            - type: addOns
              parameters:
                updateAddOns: true

            # Job: กำหนดค่า Passive Scan
            - type: passiveScan-config
              parameters:
                maxAlertsPerRule: 10
                scanOnlyInScope: true # สแกนเฉพาะ URL ที่อยู่ใน context

            # Job: Spider (Crawl เว็บไซต์เพื่อค้นหา URLs)
            - type: spider
              name: spiderStandard
              parameters:
                context: 'Juice Shop Target'
                url: 'http://localhost:3000'
                maxDuration: 5      # ระยะเวลาสูงสุดในการ spider (นาที)
                maxDepth: 5         # ความลึกสูงสุดในการ crawl
                acceptCookies: true

            # Job: AJAX Spider (สำหรับเว็บที่มีการใช้ JavaScript มาก) - Optional
            - type: ajaxSpider
              name: spiderAjax
              parameters:
                context: 'Juice Shop Target'
                url: 'http://localhost:3000'
                maxDuration: 5      # ระยะเวลาสูงสุด (นาที)
                # browserId: firefox # (Optional) ระบุ browser ID หากต้องการ
              # dependsOn: # (Optional) กำหนดให้ job นี้รันหลัง job อื่น เช่น spiderStandard
              #   - spiderStandard

            # Job: Active Scan (ค้นหาช่องโหว่เชิงรุก)
            - type: activeScan
              name: activeScanDefaultPolicy
              parameters:
                context: 'Juice Shop Target'
                policy: 'Default Policy' # นโยบายการสแกน (สามารถสร้าง custom policy ได้)
                maxScanDurationInMins: 30 # ระยะเวลาสูงสุดในการ Active Scan (นาที)
              # dependsOn:
              #   - spiderAjax # หรือ spiderStandard หากไม่ใช้ ajaxSpider

            # --- Report Generation Jobs ---
            # สร้างรายงานในรูปแบบต่างๆ

            - type: report
              name: reportTraditionalHTML
              parameters:
                template: traditional-html # Template ID สำหรับรายงาน HTML แบบดั้งเดิม
                reportDir: /zap/wrk/reports/ # Directory ภายใน container ที่จะเก็บ report
                reportFile: traditional-html-report # ชื่อไฟล์ (ZAP จะเติม .html เอง)
                reportTitle: "ZAP Traditional HTML Report for Juice Shop"
                reportDescription: "Generated by ZAP Automation Framework"
                risks: # ระดับความเสี่ยงที่ต้องการให้แสดงในรายงาน
                  - High
                  - Medium
                  - Low
                  - Informational
                confidences: # ระดับความมั่นใจ
                  - High
                  - Medium
                  - Low
                  - User Confirmed

            - type: report
              name: reportModernHTML
              parameters:
                template: modern # Template ID สำหรับรายงาน HTML แบบใหม่ (สวยงามกว่า)
                reportDir: /zap/wrk/reports/
                reportFile: modern-html-report
                reportTitle: "ZAP Modern HTML Report for Juice Shop"

            - type: report
              name: reportXML
              parameters:
                template: traditional-xml # Template ID สำหรับรายงาน XML
                reportDir: /zap/wrk/reports/
                reportFile: traditional-xml-report

            - type: report
              name: reportJSON
              parameters:
                template: traditional-json # Template ID สำหรับรายงาน JSON
                reportDir: /zap/wrk/reports/
                reportFile: traditional-json-report

            - type: report
              name: reportMarkdown
              parameters:
                template: traditional-markdown # Template ID สำหรับรายงาน Markdown
                reportDir: /zap/wrk/reports/
                reportFile: traditional-markdown-report

            # (Optional) เพิ่ม Job สำหรับ Report Template อื่นๆ ที่ ZAP รองรับ
            # เช่น 'high-level-report', 'alert-count-summary', 'risk-confidence-html'
            # - type: report
            #   parameters:
            #     template: high-level-report
            #     reportDir: /zap/wrk/reports/
            #     reportFile: high-level-summary-report
          EOF
          echo "ZAP Automation Plan created at zap-config/automation_plan.yaml"

      - name: 🚀 Start OWASP Juice Shop
        run: |
          docker pull bkimminich/juice-shop
          docker run -d --rm --name juice-shop -p 3000:3000 bkimminich/juice-shop
          echo "Juice Shop container starting..."

          echo "Waiting for Juice Shop to be fully accessible..."
          RETRY_COUNT=0
          MAX_RETRIES=15 # จำนวนครั้งสูงสุดที่จะลอง (15 * 10 วินาที = 150 วินาที timeout)
          WAIT_SECONDS=10
          until curl --output /dev/null --silent --head --fail http://localhost:3000; do
            if [ \${RETRY_COUNT} -ge \${MAX_RETRIES} ]; then
              echo "❌ Juice Shop failed to start or is not accessible after \${MAX_RETRIES} retries."
              echo "--- Juice Shop Docker Logs ---"
              docker logs juice-shop
              echo "-----------------------------"
              exit 1
            fi
            RETRY_COUNT=\$((RETRY_COUNT+1))
            echo "Waiting for Juice Shop... (Attempt \${RETRY_COUNT}/\${MAX_RETRIES})"
            sleep \${WAIT_SECONDS}
          done
          echo "✅ Juice Shop started successfully and is accessible at http://localhost:3000"

      - name: 🔎 Run OWASP ZAP Scan with Automation Framework
        run: |
          ZAP_CONFIG_DIR="\$(pwd)/zap-config"      # Directory ที่เก็บไฟล์ plan.yaml บน runner
          ZAP_REPORTS_DIR="\$(pwd)/zap-reports"   # Directory ที่จะเก็บ reports บน runner

          echo "Starting ZAP Scan using Automation Framework..."
          # ใช้ owasp/zap2docker-stable image
          # Mount ZAP configuration directory (read-only)
          # Mount ZAP reports output directory (read-write)
          # --network="host" ช่วยให้ ZAP container เข้าถึง localhost:3000 (Juice Shop) ได้ง่าย
          docker run \
            --network="host" \
            -v "\${ZAP_CONFIG_DIR}":/zap/config/:ro \
            -v "\${ZAP_REPORTS_DIR}":/zap/wrk/reports/:rw \
            --rm owasp/zap2docker-stable zap.sh -cmd \
            -autorun /zap/config/automation_plan.yaml

          echo "✅ ZAP Scan Finished. Reports should be in \${ZAP_REPORTS_DIR}"

      - name: 📊 List Generated Reports
        run: |
          echo "Contents of zap-reports directory:"
          ls -lR zap-reports
          if [ -z "\$(ls -A zap-reports)" ]; then
            echo "⚠️ Warning: No reports found in zap-reports directory."
          else
            echo "--- Checking main report files ---"
            for f in zap-reports/*.*; do
              if [ -s "\$f" ]; then
                echo "  ✅ \$f exists and is not empty."
              else
                echo "  ⚠️ Warning: \$f is missing or empty."
              fi
            done
          fi


      - name: 📤 Upload ZAP Scan Reports
        uses: actions/upload-artifact@v4
        if: always() # รัน step นี้เสมอ แม้ว่า step ก่อนหน้าจะล้มเหลว (เผื่อมี report บางส่วนถูกสร้างแล้ว)
        with:
          name: zap-scan-reports
          path: zap-reports/ # Path ไปยัง directory ที่เก็บ report
          retention-days: 7  # (Optional) ระยะเวลาที่จะเก็บ artifact นี้ไว้

      - name: 🛑 Stop OWASP Juice Shop
        if: always() # รัน step นี้เสมอ เพื่อ cleanup
        run: |
          echo "Stopping Juice Shop container..."
          docker stop juice-shop || echo "Juice Shop container not found or already stopped."